server:
  port: 9000
spring:
  application:
    name: qnp
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/QNP
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
app:
  jwtSecret: 4582d3cbd73e4ce08fd9b5d44f1a0bf62274bdc116864aeb89a122d3638ee326
